//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Model1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int Id { get; set; }
        public int CodeId { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public string NameEmployee { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
